api {
  lojista {
    url = "https://portal-staging.justa.com.vc"
  },
  appBackoffice {
    url = "https://app-staging.justa.com.vc"
  },
  justo {
    url = "https://justo-staging.justa.com.vc"
  }
  adiq {
    job-active = false
    url = "http://201.33.128.117:81/integrasi/rest/v1/merchant"
    response-base-url = "https://staging.justa.com.vc"
    username = "credenc_api@dxc.com"
    password = "Cred@api18"
    batch {
      active = true
      active-return = true
      email-success = "it-recife@justa.com.vc"
      email-error = "it-recife@justa.com.vc"
    }
    callback-ips = ["201.33.128.117", "localhost", "0:0:0:0:0:0:0:1"] # IP de retorno da Adiq para valida requisição
    channel = 170014
  }
  google {
    recaptcha {
      active = false
      url = "https://www.google.com/recaptcha/api/siteverify"
      ws-secret = "blalbalballa"
      site-secret = "blalbalballa"
    }
  }
  sendgrid {
    active = true
    key = "blalbalballasbwhhb"
  },
  phoebus {
    active = false
    url = "https://phoebus.paystore.com.br/api"
    key = "blalbalballa"
    terminalsJob = false,
  }
  infobip {
    active = false
    url = "https://api.infobip.com"
    user = "justapagamentos"
    password = "senh4hbwhwbhe"
    call {
      from = "551100058782"
      forwardTo = "5581999266439"
      #text = "Olá, eu sou a Justa. Estou transferindo sua ligação para um de nossos representantes, por favor aguarde alguns instantes."
      #textLanguage = "pt-br"
      textFileUrl = "https://s3-sa-east-1.amazonaws.com/justa-media/Vers%C3%A3o+1+Hinode.mp3"
    }
  }
  elo {
    code = "4089"
  }
  receitaws {
    active = true
    url = "https://www.receitaws.com.br/v1"
    key = "bbjhdbwegvdeh"
    daysToUpdate = 545
  }
  amazon {
    s3 {
      key = "blalbalballa"
      secret = "blalbalballa"
      bucket = "justa-portal"
    }
  }
  
  }
